name: Backend workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Set up Bun
            uses: oven-sh/setup-bun@v2
            with:
              bun-version: '1.1.38'
        
          - name: Install dependencies
            run: bun install

          - name: Run tests
            run: bun test
